// Generated by gencpp from file beginner_tutorials/unicycle.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_UNICYCLE_H
#define BEGINNER_TUTORIALS_MESSAGE_UNICYCLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct unicycle_
{
  typedef unicycle_<ContainerAllocator> Type;

  unicycle_()
    : velocity(0)
    , w(0)  {
    }
  unicycle_(const ContainerAllocator& _alloc)
    : velocity(0)
    , w(0)  {
  (void)_alloc;
    }



   typedef uint16_t _velocity_type;
  _velocity_type velocity;

   typedef uint16_t _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::beginner_tutorials::unicycle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::unicycle_<ContainerAllocator> const> ConstPtr;

}; // struct unicycle_

typedef ::beginner_tutorials::unicycle_<std::allocator<void> > unicycle;

typedef boost::shared_ptr< ::beginner_tutorials::unicycle > unicyclePtr;
typedef boost::shared_ptr< ::beginner_tutorials::unicycle const> unicycleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::unicycle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::unicycle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/chirag/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::unicycle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::unicycle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::unicycle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::unicycle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::unicycle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::unicycle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::unicycle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96e5bb2153d645eed98ac4891e1f9e0e";
  }

  static const char* value(const ::beginner_tutorials::unicycle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96e5bb2153d645eeULL;
  static const uint64_t static_value2 = 0xd98ac4891e1f9e0eULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::unicycle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/unicycle";
  }

  static const char* value(const ::beginner_tutorials::unicycle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::unicycle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 velocity\n\
uint16 w\n\
";
  }

  static const char* value(const ::beginner_tutorials::unicycle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::unicycle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct unicycle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::unicycle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::unicycle_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.velocity);
    s << indent << "w: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_UNICYCLE_H
