// Generated by gencpp from file autobotx/Unicycle.msg
// DO NOT EDIT!


#ifndef AUTOBOTX_MESSAGE_UNICYCLE_H
#define AUTOBOTX_MESSAGE_UNICYCLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace autobotx
{
template <class ContainerAllocator>
struct Unicycle_
{
  typedef Unicycle_<ContainerAllocator> Type;

  Unicycle_()
    : velocity(0)
    , w(0)  {
    }
  Unicycle_(const ContainerAllocator& _alloc)
    : velocity(0)
    , w(0)  {
  (void)_alloc;
    }



   typedef int16_t _velocity_type;
  _velocity_type velocity;

   typedef int16_t _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::autobotx::Unicycle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autobotx::Unicycle_<ContainerAllocator> const> ConstPtr;

}; // struct Unicycle_

typedef ::autobotx::Unicycle_<std::allocator<void> > Unicycle;

typedef boost::shared_ptr< ::autobotx::Unicycle > UnicyclePtr;
typedef boost::shared_ptr< ::autobotx::Unicycle const> UnicycleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autobotx::Unicycle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autobotx::Unicycle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace autobotx

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'autobotx': ['/home/chirag/catkin_ws/src/autobotx/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::autobotx::Unicycle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autobotx::Unicycle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autobotx::Unicycle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autobotx::Unicycle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autobotx::Unicycle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autobotx::Unicycle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autobotx::Unicycle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8c2016fd61b316daf4095d6aaecaac7";
  }

  static const char* value(const ::autobotx::Unicycle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8c2016fd61b316dULL;
  static const uint64_t static_value2 = 0xaf4095d6aaecaac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::autobotx::Unicycle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autobotx/Unicycle";
  }

  static const char* value(const ::autobotx::Unicycle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autobotx::Unicycle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 velocity\n\
int16 w\n\
";
  }

  static const char* value(const ::autobotx::Unicycle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autobotx::Unicycle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Unicycle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autobotx::Unicycle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autobotx::Unicycle_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.velocity);
    s << indent << "w: ";
    Printer<int16_t>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOBOTX_MESSAGE_UNICYCLE_H
